name: release

on:
  push:
    branches:
      - release

jobs:

  tag:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2
        
      - name: Make tag
        uses: tool3/bump@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          unrelated: true
          branch: release

      - name: Write tag
        uses: tool3/publisher@v1
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          scope: "@tool3"
